title: "mov eax, 64"
author: "Kevin Soules"
description: "IT security, Hardware hacking, SDR"
more: "read more"
url: "http://libdev.so"

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
  
comments:
    disqus: "eax64githubio"

style:
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/eax64/"
  - twitter: "https://twitter.com/eax64/"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
